"use client";
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from './Components/weather';

export default function Home() {

  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({})
  const [loading, setLoading] = useState(false);


  const api = {
    key: 'c9e0985a3ff4dfcc0416b4c7b8a4ba48',
    baseURL: 'https://api.openweathermap.org/data/2.5/'
  };

  const url = `${api.baseURL}weather?q=${city}&units=metric&appid=${api.key}`;


  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    });
    setCity('');
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
      <Image 
        src='https://images.unsplash.com/photo-1579619572008-3fe9f19748ea?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' 
        layout ='fill' 
        className='object-cover object-center'
        alt='Weather background'
      />

      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
        <form onSubmit={fetchWeather} 
        className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
         
          <div>
            <input 
              type='text' 
              placeholder='Search for a city' 
              value={city} 
              onChange={(e) => setCity(e.target.value)} 
              className='bg-transparent border-b-2 border-none text-white text-2xl focus:outline-none'
            />
          </div>
          <button 
            onClick={fetchWeather} 
          >
            <BsSearch size={30}/>
          </button>
        </form> 
      </div>
            
      {/* Weather */}

      {weather.main && <Weather data={weather} />}

    </div>
    );
  }
